trigger:
- main

variables:
  resourceGroupName: 'my-linux-vm-rg' 
  location: 'Central US'               
  deploymentName: 'DeployLinuxVM'      
# Steps to execute
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'             
    azureResourceManagerConnection: 'arm-template'  
    resourceGroupName: '$(resourceGroupName)'      
    location: '$(location)'                                  
    csmFile: '$(Build.SourcesDirectory)/templates/azuredeploy.json'  
    csmParametersFile: '$(Build.SourcesDirectory)/templates/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'                
    deploymentName: '$(deploymentName)'           
